### ISSUE TITLE
añadan a sas y seal team 6

### ISSUE THREAD

**Issue by MaxQuiller** [VJ-HLR-Developers/Condition-Zero-Deleted-Scenes-SNPCs#2]
hola, me gustaria que añadieran a sas y a seal team 6 para el mod, sas ya esta en el mod, pero cuando lo pongo solo sale error

**Comment by Lebert130** [comment]
what

**Comment by DrVrej** [comment]
This is English-only repository, I have translated what you wrote and it makes no sense, therefore I am going to close this.
